package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Dostavljaci;
import ba.unsa.etf.rpr.exceptions.OrderException;

import java.util.Date;
import java.util.List;

/**
 * Business Logic Layer for management of Dostavljaci
 * @author Amar Grizovic
 */
public class DostavljaciManager {
    public Dostavljaci add(Dostavljaci d) throws OrderException {
        if (d.getId() != 0)
            throw new OrderException("Can't add deliverer with ID. ID is autogenerated");
        return DaoFactory.dostavljaciDao().add(d);
    }

    public void delete(int idDostavljaca) throws OrderException{
        try{
            DaoFactory.dostavljaciDao().delete(idDostavljaca);
        }catch (OrderException e){
            if (e.getMessage().contains("FOREIGN KEY")){
                throw new OrderException("Cannot delete deliverer which is related to orders. First delete related orders before deleting deliverer.");
            }
            throw e;
        }
    }

    public Dostavljaci update(Dostavljaci d) throws OrderException{
        return DaoFactory.dostavljaciDao().update(d);
    }

    public List<Dostavljaci> getAll() throws OrderException{
        return DaoFactory.dostavljaciDao().getAll();
    }

    public List<Dostavljaci> searchByBirthDate(Date datumRodjenja) throws OrderException {
        return DaoFactory.dostavljaciDao().searchByBirthDate(datumRodjenja);
    }
}
