package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Jela;
import ba.unsa.etf.rpr.exceptions.OrderException;

import java.util.List;

/**
 * Business Logic Layer for management of Jela
 * @author Amar Grizovic
 */
public class JelaManager {
    public Jela add(Jela j) throws OrderException {
        if (j.getId() != 0)
            throw new OrderException("Can't add food with ID. ID is autogenerated");
        return DaoFactory.jelaDao().add(j);
    }

    public void delete(int idJela) throws OrderException{
        try{
            DaoFactory.jelaDao().delete(idJela);
        }catch (OrderException e){
            if (e.getMessage().contains("FOREIGN KEY")){
                throw new OrderException("Cannot delete food that is related to restaurants. First delete related restaurants before deleting food.");
            }
            throw e;
        }
    }

    public Jela update(Jela j) throws OrderException{
        return DaoFactory.jelaDao().update(j);
    }

    public List<Jela> getAll() throws OrderException{
        return DaoFactory.jelaDao().getAll();
    }
}
